blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path("",views.blog_list,name="blog_list"),
    path("<int:id>",views.blog_detail,name="blog_detail"),
    path("tag/<slug:tag>",views.blog_tag,name="tag"),
    path("category/<slug:category>",views.blog_category,name="category"),
    path("search/",views.search,name="search"),
]

foods/urls.py
from django.urls import path
from .import views

app_name = "foods"

urlpatterns = [
    path("",views.food_list,name="food_list"),
    path("<int:id>/",views.food_detail,name="detail")
]

reserveation/urls.py
from django.urls import path
from . import views

app_name = "reservation"

urlpatterns = [
    path('',views.reserve,name="reserve")
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('foods.urls')),
    path('book/', include('reserveation.urls')),
    path("blog/",include("blog.urls")),
]

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from ckeditor.fields import RichTextField

# Create your models here.

class Blog(models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    description = models.CharField(_("توضیحات"), max_length=100)
    content = RichTextField(config_name="default")
    created_at = models.DateTimeField(_("زمان انتشار"), default=timezone.now)
    author = models.ForeignKey(User, verbose_name=_("نویسنده"), on_delete=models.CASCADE)
    image = models.ImageField(_("تصویر"), upload_to="blogs/", blank = True , null = True)
    category = models.ForeignKey("Category", related_name="blog" , verbose_name=_("دسته بندی"), on_delete=models.CASCADE,blank=True, null=True)
    tags = models.ManyToManyField("Tag", verbose_name=_("تگ ها"),related_name="blogs",blank=True,null=True)
    def __str__(self):
        return self.title

class Category(models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)
    def __str__(self):
        return self.title
    
class Tag(models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)
    update_at = models.DateTimeField(_("تاریخ برزرسانی"), auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title
    
class Comments(models.Model):
    blog = models.ForeignKey("Blog", verbose_name=_("مقاله"), related_name="comments" , on_delete=models.CASCADE)
    name = models.CharField(_("نام کاربر"), max_length=100)
    email = models.EmailField(_("آدرس الکترونیکی"), max_length=254)
    message = models.TextField(_("متن نظر"))
    date = models.DateField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها"

    def __str__(self):
        return self.email

    
    

foods/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class Food(models.Model):
    FOOD_TYPE=[
        ("breakefast","صبحانه"),
        ("drinks","نوشیدنی"),
        ("dinner","شام"),
        ("lunch","ناهار")
    ]
    name = models.CharField(max_length=100)
    description = models.CharField(_("توضیحات"), max_length=50)
    rate = models.IntegerField(_("امتیاز"),default=0)
    price = models.IntegerField()
    time = models.IntegerField(_("زمان لازم"))
    pub_date = models.DateField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)
    photo = models.ImageField(upload_to='foods/')
    type_food = models.CharField(_("نوع غذا"), max_length=10,choices=FOOD_TYPE,default="drinks")

    def __str__(self):
        return self.name

reserveation/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class Reseravtion(models.Model):
    name = models.CharField(_("نام و نام خانوادگی"), max_length=200)
    email = models.EmailField(_("آدرس الکترونیکی"), max_length=254)
    phone = models.CharField(_("تلفن"), max_length=20)
    number = models.IntegerField(_("تعداد"))
    date = models.DateField(_("تاریخ"), auto_now=False, auto_now_add=False)
    time = models.TimeField(_("ساعت"), auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.email
    

blog/forms.py
from django import forms

class CommentForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=254)
    message = forms.CharField(widget=forms.Textarea)

reserveation/forms.py
from django import forms
from .models import Reseravtion

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reseravtion
        fields = "__all__"

blog/views.py
from django.shortcuts import render , get_object_or_404
from .models import Blog , Tag , Category , Comments
from .forms import CommentForm
from django.core.paginator import Paginator
# Create your views here.

def blog_list(request):
    blogs = Blog.objects.all()

    paginator = Paginator(blogs, 6) # Show 6 contacts per page.
    page_number = request.GET.get('page')
    blog_list = paginator.get_page(page_number)

    context = {
        "blog_list":blog_list
    }

    return render(request,"blog/blog_list.html",context)

def blog_detail(request,id):
    blog = Blog.objects.get(id=id)
    tags = Tag.objects.all().filter(blogs=blog)
    recents = Blog.objects.all().order_by("-created_at")[:4]
    categories = Category.objects.all()
    comments = Comments.objects.all().filter(blog=blog)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_name = form.cleaned_data['name']
            new_email = form.cleaned_data["email"]
            new_message = form.cleaned_data["message"]

            new_comment = Comments(blog=blog,name=new_name,email=new_email,message=new_message)
            new_comment.save()

    context = {
        "blog":blog,
        "tags":tags,
        "recents":recents,
        "categories":categories,
        "comments":comments,
    }
    return render(request,"blog/blog_detail.html",context)

def blog_tag(request,tag):
    blogs = Blog.objects.filter(tags__slug=tag)
    context = {
        "blogs":blogs
    }
    return render(request,"blog/blog_list.html",context)

def blog_category(request,category):
    blogs = Blog.objects.filter(category__slug=category)
    context = {
        "blogs":blogs
    }
    return render(request,"blog/blog_list.html",context)

def search(request):
    if request.method == "GET":
        q = request.GET.get("search")
    blog_list = Blog.objects.filter(title__icontains=q)
    return render(request,"blog/blog_list.html",{"blog_list":blog_list})

foods/views.py
from django.shortcuts import render
from .models import Food

# Create your views here.

def food_list(request):
    food_list = Food.objects.all()
    context = {
        "foods" : food_list
    }
    return render(request,"foods/list.html",context)


def food_detail(request , id):
    food = Food.objects.get(id = id)
    context = {
        "food":food
    }
    return render(request,"foods/detail.html",context)

reserveation/views.py
from django.shortcuts import render
from .forms import ReservationForm

# Create your views here.

def reserve(request):
    reserve_form = ReservationForm()
    if request.method == "POST":
        reserve_form = ReservationForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()
    else:
        reserve_form = ReservationForm()

    context = {
        "form":reserve_form,
    }

    return render(request,"reservation/reservation.html",context)

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-12">
                <h1>Blog</h1>
            </div>
        </div>
    </div>
</div>
<!-- End All Pages -->

<!-- Start blog details -->
<div class="blog-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>{{blog.title}}</h2>
                    <p>{{blog.description}}</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-8 col-lg-8 col-12">
                <div class="blog-inner-details-page">
                    <div class="blog-inner-box">
                        <div class="side-blog-img">
                            <img class="img-fluid" src="{{blog.image.url}}" alt="">							
                            <div class="date-blog-up">
                                27 Fab
                            </div>
                        </div>
                        <div class="inner-blog-detail details-page">
                            <h3>{{blog.description}}</h3>
                            <ul>
                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.author.first_name}} {{blog.author.last_name}}</span></li>
                                <li>|</li>
                                <li><i class="zmdi zmdi-time"></i>Time : <span>{{blog.created_at|time}}</span></li>
                            </ul>
                            <p dir="rtl">{{blog.content|safe}}</p>
                            
                        </div>
                    </div>
                    <div class="blog-comment-box">
                        <h3>Comments</h3>
                        {% for cm in comments %}
                        <div class="comment-item">
                            <div class="comment-item-left">
                                <img src="images/avt-img.jpg" alt="">
                            </div>
                            <div class="comment-item-right">
                                <div class="pull-left">
                                    <a href="#">{{cm.name}}</a>
                                </div>
                                <div class="pull-right">
                                    <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>{{cm.date}}</span>
                                </div>
                                <div class="des-l" dir="rtl">
                                    <p align="right">{{cm.message}}</p>
                                </div>
                                <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
                            </div>
                        </div>
                        {% endfor %}
                        

                        <!-- <div class="comment-item children">
                            <div class="comment-item-left">
                                <img src="images/avt-img.jpg" alt="">
                            </div>
                            <div class="comment-item-right">
                                <div class="pull-left">
                                    <a href="#">Admin</a>
                                </div>
                                <div class="pull-right">
                                    <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>1.30 pm</span>
                                </div>
                                <div class="des-l">
                                    <p>Morbi lacinia ultrices lorem id tincidunt. Cras id dui risus. Pellentesque consectetur id mi sed pharetra. Proin imperdiet gravida nisl, sit amet varius urna. In auctor.</p>
                                </div>
                                <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>
                            </div>
                        </div> -->

                    </div>
                    <div class="comment-respond-box">
                        <h3>Leave your comment </h3>
                        <div class="comment-respond-form">
                            <form id="commentrespondform" class="comment-form-respond row" method="post">
                                {% csrf_token %}
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <input id="name_com" class="form-control" name="name" placeholder="Name" type="text">
                                    </div>
                                    <div class="form-group">
                                        <input id="email_com" class="form-control" name="email" placeholder="Your Email" type="email">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <textarea class="form-control" name="message" id="textarea_com" placeholder="Your Message" rows="2"></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <button class="btn btn-submit">Submit comment</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
                <div class="right-side-blog">
                    <h3>Search</h3>
                        <form method="GET" action="{% url 'blog:search' %}">
                            <div class="blog-search-form">
                                <input name="search" placeholder="Search blog" type="text">
                                <button class="search-btn" type="submit">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                        </form>
                    <h3>Categories</h3>
                    <div class="blog-categories">
                        <ul>
                            {% for cat in categories %}
                            <li><a href="{% url 'blog:category' cat.slug %}"><span>{{cat.title}}</span></a></li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                    <h3>Recent Post</h3>
                    <div class="post-box-blog">
                        <div class="recent-post-box">
                            {% for blog in recents %}
                            <div class="recent-box-blog">
                                <div class="recent-img">
                                    <img class="img-fluid" src="{{blog.image.url}}" style="height: 70px;width:70px;" alt="">
                                </div>
                                <div class="recent-info">
                                    <ul>
                                        <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{blog.author}}</span></li>
                                        <li>|</li>
                                        <li><i class="zmdi zmdi-time"></i>Time : <span>{{blog.created_at|time}}</span></li>
                                    </ul>
                                    <h4>{{blog.description}}.</h4>
                                </div>
                            </div>

                            {% endfor %}

                        </div>
                    </div>
                    <h3>Recent Tag</h3>
                    <div class="blog-tag-box">
                        <ul class="list-inline tag-list">
                            {% for tag in tags %}
                            <li class="list-inline-item"><a href="{% url 'blog:tag' tag.slug %}">{{tag.title}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        
        </div>
    </div>
</div>
<!-- End details -->

<!-- Start Contact info -->
<div class="contact-imfo-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fa fa-volume-control-phone"></i>
                <div class="overflow-hidden">
                    <h4>Phone</h4>
                    <p class="lead">
                        +01 123-456-4590
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope"></i>
                <div class="overflow-hidden">
                    <h4>Email</h4>
                    <p class="lead">
                        yourmail@gmail.com
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-map-marker"></i>
                <div class="overflow-hidden">
                    <h4>Location</h4>
                    <p class="lead">
                        800, Lorem Street, US
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact info -->

{% endblock content %}
    

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Start All Pages -->
<div class="all-page-title page-breadcrumb">
  <div class="container text-center">
    <div class="row">
      <div class="col-lg-12">
        <h1>Blog</h1>
      </div>
    </div>
  </div>
</div>
<!-- End All Pages -->

<!-- Start blog -->
<div class="blog-box">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="heading-title text-center">
          <h2>Blog</h2>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
        </div>
      </div>
    </div>
  
    <div class="row">
      {% for blog in blog_list %}
      <div class="col-lg-4 col-md-6 col-12">
        <div class="blog-box-inner">
          <div class="blog-img-box">
            <img class="img-fluid" src="{{blog.image.url}}" style="height: 430px;" alt="">
          </div>
          <div class="blog-detail">
            <h4>{{blog.title}}</h4>
            <ul>
              <li><span>Post by {{blog.author}}</span></li>
              <li>|</li>
              <li><span>{{blog.created_at|date:"Y b d"}}</span></li>
            </ul>
            <p dir="rtl">{{blog.content|truncatewords:80}}</p>
            <a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blog:blog_detail' blog.id %}">Read More</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<!-- End blog -->

<!-- paninator -->

{% if blog_list.has_other_pages %}
<div class="container mb-3">
  <div class="row">
    <div class="col d-flex justify-content-center">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          
          {% if blog_list.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">اولین</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{blog_list.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
            
          
          {% for page in blog_list.paginator.page_range %}
            
            {% if blog_list.number == page %}
            <li class="page-item active"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
            {% endif %}
              
          {% endfor %}
          
          {% if blog_list.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{blog_list.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          <li class="page-item"><a class="page-link" href="?page={{blog_list.paginator.num_pages}}">آخرین</a></li>
          {% endif %}
            
          
        </ul>
      </nav>
    </div>
  </div>
</div>
{% endif %}
  

<!-- Start Contact info -->
<div class="contact-imfo-box">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <i class="fa fa-volume-control-phone"></i>
        <div class="overflow-hidden">
          <h4>Phone</h4>
          <p class="lead">
            +01 123-456-4590
          </p>
        </div>
      </div>
      <div class="col-md-4">
        <i class="fa fa-envelope"></i>
        <div class="overflow-hidden">
          <h4>Email</h4>
          <p class="lead">
            yourmail@gmail.com
          </p>
        </div>
      </div>
      <div class="col-md-4">
        <i class="fa fa-map-marker"></i>
        <div class="overflow-hidden">
          <h4>Location</h4>
          <p class="lead">
            800, Lorem Street, US
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Contact info -->

{% endblock content %}
	
	

foods/templates/foods/detail.html
{% extends 'base.html' %}


{% block content %}
    <img width="50%" src="{{food.photo.url}}">
    {{food.name}}
    {{food.description}}
    {{food.rate}}
{% endblock content %}
    

reserveation/templates/reservation/reservation.html
{% extends 'base.html' %}


{% block content %}
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Reservation</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->
	
	<!-- Start Reservation -->
	<div class="reservation-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>Reservation</h2>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 col-sm-12 col-xs-12">
					<div class="contact-block">
						<form method="POST" action="">
							{% csrf_token %}
							<div class="row">
								<div class="col-md-6">
									<h3>Book a table</h3>
									<div class="col-md-12">
										<div class="form-group">
											<input id="input_date" class="datepicker picker__input form-control" name="date" type="text" value="" equired data-error="Please enter Date">
											<div class="help-block with-errors"></div>
										</div>                                 
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<input id="input_time" name="time" class="time form-control picker__input" required data-error="Please enter time">
											<div class="help-block with-errors"></div>
										</div>                                 
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<select class="custom-select d-block form-control" name="number" id="person" required data-error="Please select Person">
											  <option disabled selected>Select Person*</option>
											  <option value="1">1</option>
											  <option value="2">2</option>
											  <option value="3">3</option>
											  <option value="4">4</option>
											  <option value="5">5</option>
											  <option value="6">6</option>
											  <option value="7">7</option>
											</select>
											<div class="help-block with-errors"></div>
										</div> 
									</div>
								</div>
								<div class="col-md-6">
									<h3>Contact Details</h3>
									<div class="col-md-12">
										<div class="form-group">
											<input type="text" class="form-control" id="name" name="name" placeholder="Your Name" required data-error="Please enter your name">
											<div class="help-block with-errors"></div>
										</div>                                 
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<input type="text" placeholder="Your Email" id="email" class="form-control" name="email" required data-error="Please enter your email">
											<div class="help-block with-errors"></div>
										</div> 
									</div>
									<div class="col-md-12">
										<div class="form-group">
											<input type="text" placeholder="Your Numbar" id="phone" class="form-control" name="phone" required data-error="Please enter your Numbar">
											<div class="help-block with-errors"></div>
										</div> 
									</div>
								</div>
								<div class="col-md-12">
									<div class="submit-button text-center">
										<button class="btn btn-common" id="submit" type="submit">Book Table</button>
										<div id="msgSubmit" class="h3 text-center hidden"></div> 
										<div class="clearfix"></div> 
									</div>
								</div>
							</div>            
						</form>
					</div>
				</div>
			</div>
		
			<!-- <form method="POST">
				{% csrf_token %}
				{{form}}
				<button type="submit">رزرو</button>
			</form> -->
		</div>
	</div>
	<!-- End Reservation -->
	
	<!-- Start Customer Reviews -->
	<div class="customer-reviews-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>Customer Reviews</h2>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 mr-auto ml-auto text-center">
					<div id="reviews" class="carousel slide" data-ride="carousel">
						<div class="carousel-inner mt-4">
							<div class="carousel-item text-center active">
								<div class="img-box p-1 border rounded-circle m-auto">
									<img class="d-block w-100 rounded-circle" src="images/profile-1.jpg" alt="">
								</div>
								<h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Paul Mitchel</strong></h5>
								<h6 class="text-dark m-0">Web Developer</h6>
								<p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
							</div>
							<div class="carousel-item text-center">
								<div class="img-box p-1 border rounded-circle m-auto">
									<img class="d-block w-100 rounded-circle" src="images/profile-3.jpg" alt="">
								</div>
								<h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Steve Fonsi</strong></h5>
								<h6 class="text-dark m-0">Web Designer</h6>
								<p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
							</div>
							<div class="carousel-item text-center">
								<div class="img-box p-1 border rounded-circle m-auto">
									<img class="d-block w-100 rounded-circle" src="images/profile-7.jpg" alt="">
								</div>
								<h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Daniel vebar</strong></h5>
								<h6 class="text-dark m-0">Seo Analyst</h6>
								<p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
							</div>
						</div>
						<a class="carousel-control-prev" href="#reviews" role="button" data-slide="prev">
							<i class="fa fa-angle-left" aria-hidden="true"></i>
							<span class="sr-only">Previous</span>
						</a>
						<a class="carousel-control-next" href="#reviews" role="button" data-slide="next">
							<i class="fa fa-angle-right" aria-hidden="true"></i>
							<span class="sr-only">Next</span>
						</a>
                    </div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Customer Reviews -->
	
	<!-- Start Contact info -->
	<div class="contact-imfo-box">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<i class="fa fa-volume-control-phone"></i>
					<div class="overflow-hidden">
						<h4>Phone</h4>
						<p class="lead">
							+01 123-456-4590
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-envelope"></i>
					<div class="overflow-hidden">
						<h4>Email</h4>
						<p class="lead">
							yourmail@gmail.com
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<i class="fa fa-map-marker"></i>
					<div class="overflow-hidden">
						<h4>Location</h4>
						<p class="lead">
							800, Lorem Street, US
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Contact info -->
		
{% endblock content %}
	